###
# fastq2bam workflow
##

# fastq download
get_fastq_pe:
    threads: 1
    mem: 2000
# compress fastq
gzip_fastq:
    mem: 2000
# fastp program
fastp: 
    threads: 1 
    mem: 2000
# index reference
index_ref:
    mem: 2000
# genmap map
genmap:
    threads: 1
    mem: 2000
genmap_sort:
    mem: 2000
# bwa mapping
bwa_map: 
    threads: 1 
    mem: 2000
# sort bam with picard's SortSam tool
sort_bam: 
    mem: 2000 
# mark duplicates with picard's MarkDuplicates
dedup:
    threads: 1
    mem: 2000 
# calculate BAM summaries with samtools and picard
bam_sumstats: 
    mem: 2000 
merge_bams:
    mem: 2000

###
# Intervals workflow
###

# preprocess genome, create intervals
# picard's create CreateSequenceDictionary, samtools faidx
process_ref:
    mem: 2000
# custom python algo to create intervals
create_intervals:
    mem: 5000


## Callable sites workflow

# genmap map
genmap:
    threads: 1
    mem: 2000
genmap_sort:
    mem: 2000
compute_d4:
    mem: 2000
    threads: 4
merge_d4:
    mem: 2000
callable_bed:
    mem: 2000

###
# bam2vcf workflows
###

# gatk HaplotypeCaller
bam2gvcf: 
    mem: 2000
# gatk GenomicsDBImport
gvcf2DB:
    mem: 2000
# gatk GenotypeGVCFs 
DB2vcf: 
    mem: 2000
## freebayes program only! ##
bam2vcf:
    mem: 2000
# gatk filterVcfs
filterVcfs:
    mem: 2000
# gatk GatherVcfs
gatherVcfs:
    mem: 2000
# picard SortVcf
sortVcf:
    mem: 2000
# vcftools program
vcftools:
    mem: 2000
# bedtools program
bedtools:
    mem: 2000
# plink
plink:
    threads: 5
admixture:
    mem: 2000
