##############################
# Variables you need to change
##############################

samples: "config/test_coords.csv"            # name of the sample metadata CSV 
intervals: True    #Set to True if you want to perform variant calling using interval approach. 
sentieon: False  #set to True if you want to use sentieon, False if you want GATK
sentieon_lic: "" #set to path of sentieon license
remote_reads: False # Set True if reads are in a Google Bucket seperate from --default-remote-prefix. 
remote_reads_prefix: "" # set to google bucket prefix where reads live

##############################
# Variables you *might* need to change
##############################

# Interval approach options, only applicable if intervals is True
minNmer: 500   # the minimum Nmer used to split up the genome; e.g. a value of 200 means only Nmers 200 or greater are used to define the boundaries of intervals. The minimum is 50.
num_gvcf_intervals: 1 # The maximum number of intervals to create for GVCF generation. Note: the actual number of intervals may be less than the specified value if the reference genome has very few gaps.
db_scatter_factor: 0.15 # Scatter factor for calculating number of intervals to create for genomics db generation. (scatter_factor * num_samples * num_gvcf_intervals) gives us number of db intervals to create. Reccomend <1


## Coverage options ##
## default pipeline is optimized for low coverage data - if using high coverage data (> 10x), uncomment high coverage options and comment out low coverage options
min_depth: 2
# low coverage options (< 10x) 
minP: 1
minD: 1

# high coverage options (> 10x)
#minP: 2
#minD: 4

het_prior: 0.005    #prior probabilty of heterozygous site; changes likelihood of a site being called non-ref, but not genotype likelihoods

########################################
## callable sites bed file thresholds ##
########################################

mappability_min: 1    #regions of the genome with mappability less than this will be removed from callable sites bed file
cov_threshold: 2      #regions of the genome with coverage above/below cov_thresh standard deviations will be filtered

#this ignores small regions of abberatant coverage/mappability as often these are just below the threshold
#to do strict filtering, set to 0

callable_merge: 100   #merge callable regions separated by this or fewer bp into a single region


## QC options ##
nClusters: 3
GoogleAPIKey:



########################################
## RESOURCES ##
########################################

# fastq download
get_fastq_pe:
    threads: 10
    mem: 5000
# compress fastq
gzip_fastq:
    mem: 4000
# fastp program
fastp:
    threads: 10
    mem: 5000
# index reference
index_ref:
    mem: 10000
# genmap map
genmap:
    threads: 10
    mem: 20000
genmap_sort:
    mem: 4000
  # bwa mapping
bwa_map:
    threads: 31
    mem: 15000
# sort bam with picard's SortSam tool
sort_bam:
    mem: 25000
# mark duplicates with picard's MarkDuplicates
dedup:
    threads: 31
    mem: 9000
# calculate BAM summaries with samtools and picard
bam_sumstats:
    mem: 9000
merge_bams:
    mem: 9000
bedtools:
    mem: 4000
    
###
# Intervals workflow
###

# preprocess genome, create intervals
# picard's create CreateSequenceDictionary, samtools faidx
process_ref:
    mem: 15000
# custom python algo to create intervals
create_intervals:
    mem: 5000

## Callable sites workflow

# genmap map
genmap:
    threads: 10
    mem: 20000
genmap_sort:
    mem: 4000
compute_d4:
    mem: 4000
    threads: 4
merge_d4:
    mem: 10000
callable_bed:
    mem: 10000

###
# bam2vcf workflows
###

# gatk HaplotypeCaller
bam2gvcf:
    mem: 30000
# gatk GenomicsDBImport
gvcf2DB:
    mem: 30000
# gatk GenotypeGVCFs
DB2vcf:
    mem: 30000
## freebayes program only! ##
bam2vcf:
    mem: 30000
# gatk filterVcfs
filterVcfs:
    mem: 30000
# gatk GatherVcfs
gatherVcfs:
    mem: 30000
# picard SortVcf
sortVcf:
    mem: 30000
# vcftools program
vcftools:
    mem: 30000
# bedtools program
bedtools:
    mem: 30000
# plink
plink:
    threads: 5
admixture:
    mem: 4000
