__default__:
    partition: "256x20"
    time: 9000
    nodes: 1
<<<<<<< HEAD
    output: "logs/slurm/slurm-%j.out"
=======
    output: "slurm_logs/slurm-%j.out"
    #error: "logs/slurm-%j.err"
>>>>>>> main


###
# bam2vcf_gatk
###

bam2gvcf: 
    partition: "serial_requeue"


###
# bam2vcf_fb
###

bam2vcf: 
    partition: "serial_requeue"
