__default__:
    partition: "shared"
    time: 9000
    nodes: 1
    output: "slurm_logs/{Organism}/slurm-%j.out"


###
# bam2vcf_gatk
###

bam2gvcf: 
    partition: "serial_requeue"


###
# bam2vcf_fb
###

bam2vcf: 
    partition: "serial_requeue"
